/**
 * Define placeholders for injecting original AST nodes into the transformer node
 */
module.exports = {
	TARGET_FUNCTION_PARAMETERS: '$$ANNOTATION_TARGET_FUNCTION_PARAMETERS$$',
	TARGET_FUNCTION_BODY: '$$ANNOTATION_TARGET_FUNCTION_BODY$$',
	TARGET_VARIABLE_NAME: '$$ANNOTATION_TARGET_VARIABLE_NAME$$',
	ANNOTATION_VALUE: '$$ANNOTATION_VALUE$$',
};
